# Customer Churn Prediction — Step 1: Data Understanding

**Dataset:** Telco Customer Churn (Kaggle / IBM Watson Analytics)  
**Goal:** Load the raw dataset and perform an initial inspection — no cleaning, no transformation, no modelling.

---

## 1. Import Libraries

We only need **pandas** for this step.  
`pandas` is the standard Python library for loading, inspecting, and manipulating tabular data.  
We also import `os` so we can build a file path that works regardless of where the notebook is run from.

In [1]:
import os
import pandas as pd

---
## 2. Define the Dataset Path

`os.path.join` builds an OS-agnostic file path.  
`os.path.dirname(__file__)` would give us the notebook's own directory, but inside Jupyter the equivalent is to navigate relative to the notebook location.  
Here we go **one level up** from `notebook/` to reach the project root, then down into `data/`.  
This makes the path work whether you run the notebook from any directory.

In [2]:
# Build a path relative to the notebook's location so it works on any machine
NOTEBOOK_DIR = os.path.abspath('')          # current working directory when running this cell
PROJECT_ROOT = os.path.dirname(NOTEBOOK_DIR) if os.path.basename(NOTEBOOK_DIR) == 'notebook' else NOTEBOOK_DIR
DATA_PATH = os.path.join(PROJECT_ROOT, 'data', 'WA_Fn-UseC_-Telco-Customer-Churn.csv')

print('Dataset path:', DATA_PATH)
print('File exists :', os.path.exists(DATA_PATH))

Dataset path: C:\Users\Subham\OneDrive\Documents\Desktop\Customer_Churn_Project\data\WA_Fn-UseC_-Telco-Customer-Churn.csv
File exists : True

---
## 3. Load the Dataset

`pd.read_csv()` reads a comma-separated values file and returns a **DataFrame** — pandas' core 2-D table structure.  
No arguments beyond the file path are passed here because we want to load the data **exactly as it is** in the raw file without applying any parsing tricks or type coercions.

In [3]:
df = pd.read_csv(DATA_PATH)

print('Dataset loaded successfully.')

Dataset loaded successfully.

---
## 4. First 5 Rows — `df.head()`

`df.head(5)` returns the **first 5 rows** of the DataFrame as a formatted table.  
This gives an immediate visual check that:
- The file was read correctly.
- Column headers were parsed from the first row.
- Values look as expected (no obvious encoding issues, correct delimiters, etc.).

In [4]:
df.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

---
## 5. Dataset Shape — `df.shape`

`df.shape` returns a tuple **(rows, columns)**.  
- **Rows** = the number of customer records in the dataset.  
- **Columns** = the number of features (variables) available for each customer.  

Knowing the dimensions upfront helps us understand the scale of the data before doing anything else.

In [5]:
rows, cols = df.shape

print(f'Number of rows    (customer records) : {rows}')
print(f'Number of columns (features)         : {cols}')

Number of rows    (customer records) : 7043
Number of columns (features)         : 21

---
## 6. Column Names — `df.columns`

`df.columns` returns an **Index** of all column names.  
Printing them lets us:
- Confirm every expected feature is present.
- Spot any typos or unusual naming conventions.
- Plan ahead for future cleaning and feature engineering steps.

We enumerate them with their index numbers so they are easier to reference.

In [6]:
print(f'Total columns: {len(df.columns)}\n')
print('Column index  |  Column name')
print('-' * 40)
for i, col in enumerate(df.columns):
    print(f'  {i:>2}          |  {col}')

Total columns: 21

Column index  |  Column name
----------------------------------------
   0          |  customerID
   1          |  gender
   2          |  SeniorCitizen
   3          |  Partner
   4          |  Dependents
   5          |  tenure
   6          |  PhoneService
   7          |  MultipleLines
   8          |  InternetService
   9          |  OnlineSecurity
  10          |  OnlineBackup
  11          |  DeviceProtection
  12          |  TechSupport
  13          |  StreamingTV
  14          |  StreamingMovies
  15          |  Contract
  16          |  PaperlessBilling
  17          |  PaymentMethod
  18          |  MonthlyCharges
  19          |  TotalCharges
  20          |  Churn

---
## 7. Quick Summary — `df.info()`

`df.info()` prints a concise summary that shows, for every column:
- The **data type** pandas inferred (`int64`, `float64`, `object`, etc.).
- The **non-null count** — any column with fewer non-null entries than total rows has missing values.

This is purely observational here. We are **not fixing anything yet** — we are only noting what we see for the data quality analysis that comes in Step 2.

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

---
## 8. Basic Descriptive Statistics — `df.describe()`

`df.describe()` computes summary statistics (count, mean, std, min, quartiles, max) for every **numeric** column.  
Passing `include='all'` also shows basic stats for **categorical / object** columns (unique count, top value, frequency).  

Again — purely observational. Nothing is changed.

In [8]:
df.describe(include='all')

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
count,7043,7043,7043.000000,7043,7043,7043.000000,7043,7043,7043,7043,...,7043,7043,7043,7043,7043,7043,7043,7043.000000,7043,7043
unique,7043,2,NaN,2,2,NaN,2,3,3,3,...,3,3,3,3,3,2,4,NaN,6531,2
top,7590-VHVEG,Male,NaN,No,No,NaN,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,NaN,,No
freq,1,3555,NaN,3641,4933,NaN,6361,3390,3096,3498,...,3095,3473,2810,2785,3875,4171,2365,NaN,11,5174
mean,NaN,NaN,0.162147,NaN,NaN,32.371149,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.761692,NaN,NaN
std,NaN,NaN,0.368612,NaN,NaN,24.559481,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.090047,NaN,NaN
min,NaN,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.250000,NaN,NaN
25%,NaN,NaN,0.000000,NaN,NaN,9.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.500000,NaN,NaN
50%,NaN,NaN,0.000000,NaN,NaN,29.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.350000,NaN,NaN
75%,NaN,NaN,0.000000,NaN,NaN,55.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.850000,NaN,NaN
max,NaN,NaN,1.000000,NaN,NaN,72.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.750000,NaN,NaN

---
## ✅ Step 1 Complete

| Check | Result |
|---|---|
| Dataset loaded | ✓ |
| First 5 rows displayed | ✓ |
| Shape (rows × columns) printed | ✓ |
| All column names listed | ✓ |
| Data types and null counts noted | ✓ |
| Descriptive statistics noted | ✓ |
| Any data modified / cleaned | ✗ — raw data untouched |
| Any ML model trained | ✗ — not yet |

**Next step →** Step 2: Data Quality Analysis (missing values, duplicates, type issues, outlier detection).